spring.application.name=gestionClientsMRF
server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5432/gestion_pharmacie
spring.datasource.username=postgres
spring.datasource.password=passadmin
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

